package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.67

import (
	"context"
	"fmt"
	"ismartcoding/plainnas/internal/db"
	"ismartcoding/plainnas/internal/graph/generated"
	"ismartcoding/plainnas/internal/graph/helpers"
	"ismartcoding/plainnas/internal/graph/model"
	"ismartcoding/plainnas/internal/media"
	"strings"
)

// SetDeviceName is the resolver for the setDeviceName field.
func (r *mutationResolver) SetDeviceName(ctx context.Context, name string) (bool, error) {
	return setDeviceNameModel(ctx, name)
}

// SetKeyValue is the resolver for the setKeyValue field.
func (r *mutationResolver) SetKeyValue(ctx context.Context, key string, value string) (bool, error) {
	db.SetValue(key, value)
	return true, nil
}

// DeleteKeyValue is the resolver for the deleteKeyValue field.
func (r *mutationResolver) DeleteKeyValue(ctx context.Context, key string) (bool, error) {
	db.DeleteValue(key)
	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	return logout(ctx)
}

// RevokeSession is the resolver for the revokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, clientID string) (bool, error) {
	return revokeSession(ctx, clientID)
}

// SetMediaSourceDirs is the resolver for the setMediaSourceDirs field.
func (r *mutationResolver) SetMediaSourceDirs(ctx context.Context, dirs []string) (bool, error) {
	return setMediaSourceDirsModel(ctx, dirs)
}

// SetSambaSettings is the resolver for the setSambaSettings field.
func (r *mutationResolver) SetSambaSettings(ctx context.Context, input model.SambaSettingsInput) (bool, error) {
	return setSambaSettings(ctx, input)
}

// SetSambaUserPassword is the resolver for the setSambaUserPassword field.
func (r *mutationResolver) SetSambaUserPassword(ctx context.Context, password string) (bool, error) {
	return setSambaUserPassword(ctx, password)
}

// AddFavoriteFolder is the resolver for the addFavoriteFolder field.
func (r *mutationResolver) AddFavoriteFolder(ctx context.Context, rootPath string, relativePath string) (*model.FavoriteFolder, error) {
	return addFavoriteFolder(rootPath, relativePath)
}

// RemoveFavoriteFolder is the resolver for the removeFavoriteFolder field.
func (r *mutationResolver) RemoveFavoriteFolder(ctx context.Context, rootPath string, relativePath string) (*model.FavoriteFolder, error) {
	return removeFavoriteFolder(rootPath, relativePath)
}

// SetFavoriteFolderAlias is the resolver for the setFavoriteFolderAlias field.
func (r *mutationResolver) SetFavoriteFolderAlias(ctx context.Context, rootPath string, relativePath string, alias string) (bool, error) {
	return setFavoriteFolderAlias(rootPath, relativePath, alias)
}

// CreateDir is the resolver for the createDir field.
func (r *mutationResolver) CreateDir(ctx context.Context, path string) (*model.File, error) {
	return createDirModel(ctx, path)
}

// WriteTextFile is the resolver for the writeTextFile field.
func (r *mutationResolver) WriteTextFile(ctx context.Context, path string, content string, overwrite bool) (*model.File, error) {
	return writeTextFileModel(ctx, path, content, overwrite)
}

// RenameFile is the resolver for the renameFile field.
func (r *mutationResolver) RenameFile(ctx context.Context, path string, name string) (bool, error) {
	return renameFileModel(ctx, path, name)
}

// CopyFile is the resolver for the copyFile field.
func (r *mutationResolver) CopyFile(ctx context.Context, src string, dst string, overwrite bool) (bool, error) {
	return copyFileOp(src, dst, overwrite)
}

// MoveFile is the resolver for the moveFile field.
func (r *mutationResolver) MoveFile(ctx context.Context, src string, dst string, overwrite bool) (bool, error) {
	return moveFileOp(src, dst, overwrite)
}

// CreateCopyTask is the resolver for the createCopyTask field.
func (r *mutationResolver) CreateCopyTask(ctx context.Context, ops []*model.FileTaskOpInput) (*model.FileTask, error) {
	return createCopyTaskModel(ctx, ops)
}

// CreateMoveTask is the resolver for the createMoveTask field.
func (r *mutationResolver) CreateMoveTask(ctx context.Context, ops []*model.FileTaskOpInput) (*model.FileTask, error) {
	return createMoveTaskModel(ctx, ops)
}

// DeleteFiles is the resolver for the deleteFiles field.
func (r *mutationResolver) DeleteFiles(ctx context.Context, paths []string) (bool, error) {
	return deleteFiles(paths)
}

// TrashFiles is the resolver for the trashFiles field.
func (r *mutationResolver) TrashFiles(ctx context.Context, paths []string) (bool, error) {
	return trashFiles(paths)
}

// RestoreFiles is the resolver for the restoreFiles field.
func (r *mutationResolver) RestoreFiles(ctx context.Context, paths []string) (bool, error) {
	return restoreFiles(paths)
}

// SetTempValue is the resolver for the setTempValue field.
func (r *mutationResolver) SetTempValue(ctx context.Context, key string, value string) (*model.TempValue, error) {
	if strings.TrimSpace(key) == "" {
		return nil, fmt.Errorf("key is empty")
	}
	// store under temp: namespace
	if err := db.GetDefault().Set([]byte("temp:"+key), []byte(value), nil); err != nil {
		return nil, err
	}
	return &model.TempValue{Key: key, Value: value}, nil
}

// MergeChunks is the resolver for the mergeChunks field.
func (r *mutationResolver) MergeChunks(ctx context.Context, fileID string, totalChunks int, path string, replace bool) (string, error) {
	return mergeChunks(fileID, totalChunks, path, replace)
}

// StartMediaScan is the resolver for the startMediaScan field.
func (r *mutationResolver) StartMediaScan(ctx context.Context, root string) (bool, error) {
	go media.ScanAndSync(root)
	return true, nil
}

// PauseMediaScan is the resolver for the pauseMediaScan field.
func (r *mutationResolver) PauseMediaScan(ctx context.Context) (bool, error) {
	media.PauseScan()
	return true, nil
}

// ResumeMediaScan is the resolver for the resumeMediaScan field.
func (r *mutationResolver) ResumeMediaScan(ctx context.Context) (bool, error) {
	media.ResumeScan()
	return true, nil
}

// StopMediaScan is the resolver for the stopMediaScan field.
func (r *mutationResolver) StopMediaScan(ctx context.Context) (bool, error) {
	stopMediaScan()
	return true, nil
}

// RebuildMediaIndex is the resolver for the rebuildMediaIndex field.
func (r *mutationResolver) RebuildMediaIndex(ctx context.Context, root string) (bool, error) {
	rebuildMediaIndex(root)
	return true, nil
}

// AddPlaylistAudios is the resolver for the addPlaylistAudios field.
func (r *mutationResolver) AddPlaylistAudios(ctx context.Context, query string) (bool, error) {
	return addPlaylistAudios(query)
}

// ReorderPlaylistAudios is the resolver for the reorderPlaylistAudios field.
func (r *mutationResolver) ReorderPlaylistAudios(ctx context.Context, paths []string) (bool, error) {
	return reorderPlaylistAudios(paths)
}

// PlayAudio is the resolver for the playAudio field.
func (r *mutationResolver) PlayAudio(ctx context.Context, path string) (*model.PlaylistAudio, error) {
	return playAudio(path)
}

// UpdateAudioPlayMode is the resolver for the updateAudioPlayMode field.
func (r *mutationResolver) UpdateAudioPlayMode(ctx context.Context, mode model.MediaPlayMode) (bool, error) {
	return updateAudioPlayMode(mode)
}

// ClearAudioPlaylist is the resolver for the clearAudioPlaylist field.
func (r *mutationResolver) ClearAudioPlaylist(ctx context.Context) (bool, error) {
	return clearAudioPlaylist()
}

// DeletePlaylistAudio is the resolver for the deletePlaylistAudio field.
func (r *mutationResolver) DeletePlaylistAudio(ctx context.Context, path string) (bool, error) {
	return deletePlaylistAudio(path)
}

// TrashMediaItems is the resolver for the trashMediaItems field.
func (r *mutationResolver) TrashMediaItems(ctx context.Context, typeArg model.DataType, query string) (*model.MediaActionResult, error) {
	return trashMediaItems(typeArg, query)
}

// RestoreMediaItems is the resolver for the restoreMediaItems field.
func (r *mutationResolver) RestoreMediaItems(ctx context.Context, typeArg model.DataType, query string) (*model.MediaActionResult, error) {
	return restoreMediaItems(typeArg, query)
}

// DeleteMediaItems is the resolver for the deleteMediaItems field.
func (r *mutationResolver) DeleteMediaItems(ctx context.Context, typeArg model.DataType, query string) (*model.MediaActionResult, error) {
	return deleteMediaItems(typeArg, query)
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, typeArg model.DataType, name string) (*model.Tag, error) {
	return createTag(typeArg, name)
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, id string, name string) (*model.Tag, error) {
	return updateTag(id, name)
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id string) (bool, error) {
	return deleteTag(id)
}

// AddToTags is the resolver for the addToTags field.
func (r *mutationResolver) AddToTags(ctx context.Context, typeArg model.DataType, tagIds []string, query string) (bool, error) {
	return addToTags(typeArg, tagIds, query)
}

// UpdateTagRelations is the resolver for the updateTagRelations field.
func (r *mutationResolver) UpdateTagRelations(ctx context.Context, typeArg model.DataType, item model.TagRelationStub, addTagIds []string, removeTagIds []string) (bool, error) {
	return updateTagRelations(typeArg, item, addTagIds, removeTagIds)
}

// RemoveFromTags is the resolver for the removeFromTags field.
func (r *mutationResolver) RemoveFromTags(ctx context.Context, typeArg model.DataType, tagIds []string, query string) (bool, error) {
	return removeFromTags(typeArg, tagIds, query)
}

// SetMountAlias is the resolver for the setMountAlias field.
func (r *mutationResolver) SetMountAlias(ctx context.Context, id string, alias string) (bool, error) {
	return setMountAlias(id, alias)
}

// FormatDisk is the resolver for the formatDisk field.
func (r *mutationResolver) FormatDisk(ctx context.Context, path string) (bool, error) {
	return formatDisk(ctx, path)
}

// DlnaCast is the resolver for the dlnaCast field.
func (r *mutationResolver) DlnaCast(ctx context.Context, rendererUdn string, url string, title string, mime string, typeArg model.DataType) (bool, error) {
	return dlnaCastModel(ctx, rendererUdn, url, title, mime, typeArg)
}

// App is the resolver for the app field.
func (r *queryResolver) App(ctx context.Context) (*model.App, error) {
	return app(ctx)
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context) ([]*model.Session, error) {
	return listSessions(ctx)
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, limit int) ([]*model.Event, error) {
	return listEvents(ctx, limit)
}

// FavoriteFolders is the resolver for the favoriteFolders field.
func (r *queryResolver) FavoriteFolders(ctx context.Context) ([]*model.FavoriteFolder, error) {
	return favoriteFoldersList(), nil
}

// GetTasks is the resolver for the getTasks field.
func (r *queryResolver) GetTasks(ctx context.Context) ([]*model.FileTask, error) {
	return getTasksModel(ctx)
}

// Mounts is the resolver for the mounts field.
func (r *queryResolver) Mounts(ctx context.Context) ([]*model.StorageMount, error) {
	return ListMounts()
}

// Disks is the resolver for the disks field.
func (r *queryResolver) Disks(ctx context.Context) ([]*model.StorageDisk, error) {
	return ListStorageDisks()
}

// MediaSourceDirs is the resolver for the mediaSourceDirs field.
func (r *queryResolver) MediaSourceDirs(ctx context.Context) ([]string, error) {
	return db.GetMediaSourceDirs(), nil
}

// SambaSettings is the resolver for the sambaSettings field.
func (r *queryResolver) SambaSettings(ctx context.Context) (*model.SambaSettings, error) {
	return sambaSettings(ctx)
}

// Images is the resolver for the images field.
func (r *queryResolver) Images(ctx context.Context, offset int, limit int, query string, sortBy model.FileSortBy) ([]*model.Image, error) {
	items, _ := helpers.ScanImages(offset, limit, query, sortBy)
	return items, nil
}

// ImageCount is the resolver for the imageCount field.
func (r *queryResolver) ImageCount(ctx context.Context, query string) (int, error) {
	return helpers.CountMedia(query, "image")
}

// RecentFilesCount is the resolver for the recentFilesCount field.
func (r *queryResolver) RecentFilesCount(ctx context.Context) (int, error) {
	return recentFilesCount()
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, typeArg model.DataType) ([]*model.Tag, error) {
	return listTags(typeArg)
}

// MediaBuckets is the resolver for the mediaBuckets field.
func (r *queryResolver) MediaBuckets(ctx context.Context, typeArg model.DataType) ([]*model.MediaBucket, error) {
	return listMediaBuckets(typeArg)
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context, offset int, limit int, query string, sortBy model.FileSortBy) ([]*model.Video, error) {
	items, _ := helpers.ScanVideos(offset, limit, query, sortBy)
	return items, nil
}

// Audios is the resolver for the audios field.
func (r *queryResolver) Audios(ctx context.Context, offset int, limit int, query string, sortBy model.FileSortBy) ([]*model.Audio, error) {
	items, _ := helpers.ScanAudios(offset, limit, query, sortBy)
	return items, nil
}

// AudioCount is the resolver for the audioCount field.
func (r *queryResolver) AudioCount(ctx context.Context, query string) (int, error) {
	return helpers.CountMedia(query, "audio")
}

// VideoCount is the resolver for the videoCount field.
func (r *queryResolver) VideoCount(ctx context.Context, query string) (int, error) {
	return helpers.CountMedia(query, "video")
}

// DeviceInfo is the resolver for the deviceInfo field.
func (r *queryResolver) DeviceInfo(ctx context.Context) (*model.DeviceInfo, error) {
	return buildDeviceInfo()
}

// AppUpdate is the resolver for the appUpdate field.
func (r *queryResolver) AppUpdate(ctx context.Context) (*model.AppUpdate, error) {
	return buildAppUpdate(ctx)
}

// PathStat is the resolver for the pathStat field.
func (r *queryResolver) PathStat(ctx context.Context, path string) (*model.PathStat, error) {
	return pathStatModel(path)
}

// PathStats is the resolver for the pathStats field.
func (r *queryResolver) PathStats(ctx context.Context, paths []string) ([]*model.PathStatResult, error) {
	return pathStatsModel(paths)
}

// FileInfo is the resolver for the fileInfo field.
func (r *queryResolver) FileInfo(ctx context.Context, id string, path string, includeDirSize *bool) (*model.FileInfo, error) {
	return buildFileInfo(ctx, id, path, includeDirSize != nil && *includeDirSize)
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, offset int, limit int, query string, sortBy model.FileSortBy) ([]*model.File, error) {
	return files(offset, limit, query, sortBy)
}

// FilesCount is the resolver for the filesCount field.
func (r *queryResolver) FilesCount(ctx context.Context, query string) (int, error) {
	return filesCount(query)
}

// RecentFiles is the resolver for the recentFiles field.
func (r *queryResolver) RecentFiles(ctx context.Context) ([]*model.File, error) {
	return recentFiles()
}

// TrashCount is the resolver for the trashCount field.
func (r *queryResolver) TrashCount(ctx context.Context) (int, error) {
	return trashCount()
}

// UploadedChunks is the resolver for the uploadedChunks field.
func (r *queryResolver) UploadedChunks(ctx context.Context, fileID string) ([]int, error) {
	return uploadedChunks(fileID)
}

// DlnaRenderers is the resolver for the dlnaRenderers field.
func (r *queryResolver) DlnaRenderers(ctx context.Context) ([]*model.DlnaRenderer, error) {
	return dlnaRenderersModel(ctx)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
